DROP DATABASE IF EXISTS foodapp;
CREATE DATABASE foodapp;

\c foodapp;

CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(100) NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  pass VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS restaurants (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(100) NOT NULL,
  address VARCHAR(255) NOT NULL,
  neighborhood VARCHAR(200) NOT NULL,
  cuisine VARCHAR(200) NOT NULL,
  total_visits INT NOT NULL,
  admin VARCHAR(255) NOT NULL,
  pass VARCHAR(255) NOT NULL
);